# Generated by Django 2.2.10 on 2021-02-03 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmdTypes',
            fields=[
                ('cmd_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('poll_title', models.TextField()),
                ('poll_start', models.IntegerField()),
                ('poll_end', models.IntegerField()),
                ('poll_description', models.TextField(blank=True, null=True)),
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('question_type', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Groups')),
            ],
        ),
        migrations.CreateModel(
            name='Usersanswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('timestamp', models.IntegerField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Polls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_title', models.TextField()),
                ('question_choices', models.TextField(blank=True, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Polls')),
                ('question_type', models.ForeignKey(db_column='question_type', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.QuestionTypes')),
            ],
        ),
        migrations.AddField(
            model_name='polls',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Users'),
        ),
        migrations.CreateModel(
            name='AdminLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_text', models.TextField(blank=True, null=True)),
                ('cmd', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.CmdTypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Users')),
            ],
        ),
    ]
